print("Greetings")
users_name = input("Please Enter your Name:\n")
username = input(users_name + " Please Enter a username:\n")
users_password = input("Please Enter a Password:\n")
users_email_id = input("Please provide Your Email id")
users_phone_number = input("Please provide Your Phone Number")
input(users_name + " Your Credentials have been Succesfully Saved!")